const hraInputs = {
	age_in_years: '',
	arrested_dui: '',
	blood_pressure_estimated: 'not_answered',
	blood_pressure_measured_low_number: '',
	blood_pressure_measured_high_number: '',
	blood_pressure_medication: '',
	body_frame_size: 'not_answered',
	blood_glucose: '',
	blood_glucose_mml: '',
	bicycle_helmet_usage: '',
	binge_drinking: '',
	butter: 'not answered',
	caffeine: '',
	charcoal_broiled: '',
	chh_cough: 'not answered',
	chh_fever: 'not answered',
	chh_hands: 'not_answered',
	chh_interact: 'not answered',
	chh_sbreath: 'not answered',
	cholesterol_check: 'not_answered',
	cholesterol_level: '',
	cholesterol_level_mml: '',
	cholesterol_level_estimated: 'not_answered',
	cholesterol_medication: '',
	commercial_driver: '',
	colon_cancer_screening: '',
	cross_contamination: '',
	desserts: 'not answered',
	diabetes_status: '',
	daily_cigars: '',
	daily_pipes: '',
	daily_shisha: '',
	daily_marajuana: '',
	difficulties_piling_up: '',
	distracted_driving: '',
	drinking_and_driving: '',
	driving_speed: '',
	education: '',
	fast_food: 'not answered',
	felt_confident: '',
	filling_forms: '',
	fish: '',
	fruit: 'not answered',
	fruits_and_vegetables: '',
	GADa: '',
	GADb: '',
	GADc: '',
	GADe: '',
	GADd: '',
	GADf: '',
	GADg: '',
	gainful_employment: '',
	going_your_way: '',
	gross_weight: '',
	hb1ac_check: '',
	hdl_cholesterol: '',
	hdl_cholesterol_mml: '',
	hdl_cholesterol_estimated: 'not_answered',
	health_information_interest: '',
	heart_disease: '',
	heart_attack: '',
	height: '',
	height_cm: '',
	height_feet: '',
	height_inches: '',
	helmet_usage: '',
	high_cholesterol_food: '',
	hispanic_origin: '',
	home_safety: '',
	household_income: '',
	hysterectomy: '',
	insurance_coverage: '',
	junk_food: 'not answered',
	last_mammogram: '',
	marital_status: '',
	misfortune: '',
	overall_health: '',
	pap_smear_test: '',
	PHQa: '',
	PHQb: '',
	PHQc: '',
	PHQd: '',
	PHQe: '',
	PHQf: '',
	PHQg: '',
	PHQh: '',
	PHQi: '',
	protein: 'not answered',
	race: '',
	road_rage: '',
	readiness_to_quit_smoking: '',
	readiness_to_exercise_more: '',
	readiness_to_eat_healthier: '',
	readiness_to_reduce_alcohol_usage: '',
	resting_heart_rate: '',
	sex: 'not_answered',
	sleep1: 'not answered',
	sleep2: 'not answered',
	sleep3: 'not answered',
	sleep4: 'not answered',
	soft_drinks: 'not answered',
	stroke: '',
	safety_belt_usage: '',
	stage: '',
	still_smoke: '',
	save_key: '',
	smoking: '',
	smokeless_tobacco: '',
	state_of_residence: '',
	sugar_beverage: '',
	typical_travel_method: 'not_answered',
	type_of_license: '',
	travel_by_automobile: '',
	travel_by_automobile_km: '',
	triglycerides: '',
	travel_by_motorcycle: '',
	travel_by_motorcycle_km: '',
	unable_to_control: '',
	used_to_smoke_cigarettes_day: '',
	used_to_smoke_cigars_day: '',
	used_to_smoke_pipes_day: '',
	vegetables: 'not answered',
	vaping: '',
	vaping_freq: '',
	weight: '',
	weight_kg: '',
	weekly_alcohol_beer: '',
	weekly_alcohol_wine: '',
	weekly_alcohol_wine_coolers: '',
	weekly_alcohol_mixed_drinks: '',
	weekly_physical_activity: '',
	years_as_driver: '',
	years_since_quitting_years: '',
	years_since_quitting_months: ''
};


export default hraInputs;